### ISSUE TITLE
testsql.jsがエラーを吐く

### ISSUE THREAD

**Issue by kibehiro** [rkclhack/hackathon-o-D#14]
DB周りが更新されたということで、pullしてtestsql.jsを実行したところ
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_ERROR: no such table: chat
Emitted 'error' event at:
```
といったエラーがでました

すでにあってDBファイルを消してから実行したところ、このエラーが出ました

**Comment by kibehiro** [comment]
一応自分でコマンドをコピーしてテーブルを作ったのですが、それでも入れませんでした
リストアするとき用のダミーデータも必要……？

**Comment by kei-uma** [comment]
@kibehiro 
DBのinitが実行されていなかったので修正しました。

**Comment by kibehiro** [comment]
プルリク動作確認しました！
/roomに入れないのは俺だけですかね？
もし修正案件なら、別々のPull requestにします？

**Comment by kei-uma** [comment]
@kibehiro 
roomのDBを消去されてtestsqlを実行されましたか？

**Comment by kibehiro** [comment]
@kei-uma 
アッ！

**Comment by kibehiro** [comment]
@kei-uma 
したけど動きませんでした……

**Comment by kei-uma** [comment]
@kibehiro 
なんてエラーがでてますか？？

**Comment by kibehiro** [comment]
(node:32338) UnhandledPromiseRejectionWarning: #<ModelError>
(node:32338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kibehiro** [comment]
現状のコードだと、roomにダミーデータが入ってないからエラーが出てるのかなとは思ってるんですが、的外れですかね？

**Comment by kei-uma** [comment]
@kibehiro 
そのようですね。
こちらもエラー確認できました。
修正しますね。

**Comment by kibehiro** [comment]
お手数ですがお願いします！🙏

**Comment by kei-uma** [comment]
修正完了しました

**Comment by kibehiro** [comment]
動作確認しました！
マージします！
